rules_phase1 = [
    {'rule': 'The difference between successive list items must be constant.',
     'short_rule': 'constant differences',
     'example': [2, 5, 8, 11],
     'difficulty': 0.25,
     },
    {'rule': 'There are no repeated numbers in the list.',
     'short_rule': 'no repeats',
     'example': [4, 11, 8, 6],
     'difficulty': 2.30,
     },
    {'rule': 'All list members are one less than a number with an integer square root.',
     'short_rule': 'decremented square',
     'example': [24, 48, 8, 15],
     'difficulty': 2.35,
     },
    {'rule': 'The first item is duplicated somewhere in the list (eg [17, 4, 8, 17])',
     'short_rule': 'first item duplicated',
     'example': [14, 7, 9, 14],
     'difficulty': 2.35,
     },
    {'rule': 'Differences between successive members of the list are alternately positive and negative (so for example [6, 3, 5, 3, 17, 2, 8, 5] would match the rule).',
     'short_rule': 'alternating increase decrease',
     'example': [22, 17, 19, 9, 12],
     'difficulty': 2.45,
     },
    {'rule': 'No members of the list are prime numbers.',
     'short_rule': 'no primes',
     'example': [22, 15, 6, 9],
     'difficulty': 2.50,
     },
    {'rule': 'The sum of all list items is 20.',
     'short_rule': 'sum to 20',
     'example': [4, 7, 6, 3],
     'difficulty': 2.45,
     },
    {'rule': 'The list contains exactly one prime number',
     'short_rule': 'one prime',
     'example': [4, 7, 12, 18],
     'difficulty': 3.55,
     },
]

rules_phase2_pt1 = [
    {'rule': 'List items must be in strictly increasing order',
     'short_rule': 'strictly increasing order',
     'example': [2, 5, 7, 14],
     'difficulty': 1.10,
     },
    {'rule': 'There are no repeated numbers in the list.',
     'short_rule': 'no repeated numbers',
     'example': [4, 11, 8, 6],
     'difficulty': 2.30,
     },
    {'rule': 'All list items are a multiple of 3 or 5, but are not a multiple of 15.',
     'short_rule': 'mult 3 or 5 not both',
     'example': [9, 25, 12, 10],
     'difficulty': 2.45,
     },
    {'rule': 'Each element must be in between the preceding two elements (the first two elements can be anything)',
     'short_rule': 'converging toward center',
     'example': [5, 24, 17, 21],
     'difficulty': 3.05,
     },
    {'rule': 'The list must contain an odd number of odd numbers',
     'short_rule': 'odd number of odd numbers',
     'example': [15, 7, 12, 9],
     'difficulty': 3.25,
     },
    {'rule': 'The number of elements in the list must be prime',
     'short_rule': 'prime number of elements',
     'example': [8, 13, 2, 12, 5],
     'difficulty': 3.40,
     },
    {'rule': 'Each element is the list is either a) the sum of the preceding two elements or b) a repeat of the preceding number. The first element can be anything.',
     'short_rule': 'previous or sum',
     'example': [3, 3, 6, 9, 9, 18],
     'difficulty': 3.70,
     },
    {'rule': 'If a list item n is even, the next item must be (n / 2). Otherwise (ie if n is odd), the next item must be (5 * n + 1). For example, [12, 6, 3, 10, 5, 16] follows the rule.',
     'short_rule': 'collatzish',
     'example': [12, 6, 3, 10, 5, 16],
     'difficulty': 3.95,
     },
    {'rule': 'Each element is either divisible by the previous element, or is equal to the previous element plus 13. For example [2, 6, 19, 38, 51]',
     'short_rule': 'divisible or plus 13',
     'example': [2, 6, 19, 38, 51],
     'difficulty': 4.35,
     },
    {'rule': 'Each item is equal to the first non-zero digit of (previous_item / 17). For example, [4, 2, 1, 5, 2]',
     'short_rule': 'previous over 17',
     'example': [4, 2, 1, 5, 2],
     'difficulty': 4.70,
     },
]

phase1_models = ['google/gemma-2-27b-it', 'qwen/qwq-32b-preview', 'meta-llama/llama-3.3-70b-instruct', 'openai/gpt-4o-2024-11-20', 'google/gemini-exp-1206:free', 'anthropic/claude-3.5-sonnet:beta']
phase2_models = ['meta-llama/llama-3.3-70b-instruct', 'qwen/qwq-32b-preview', 'openai/gpt-4o-2024-11-20', 'openai/o1-preview', 'anthropic/claude-3.5-sonnet:beta']
